compute_environment: LOCAL_MACHINE  
distributed_type: FSDP  
mixed_precision: bf16  

machine_rank: 0  
num_processes: 4  

main_process_ip: 127.0.0.1  
main_process_port: 29500  

fsdp_config:  
  auto_wrap_policy: TRANSFORMER_BASED_WRAP  
  backward_prefetch_policy: BACKWARD_PRE  
  cpu_offload_params: false  
  sharding_strategy: FULL_SHARD  
  state_dict_type: SHARDED_STATE_DICT  
  sync_module_states: true  
  use_orig_params: true  
  cpu_ram_efficient_loading: true  
